### ISSUE TITLE
auto-importing encountered an error

### ISSUE THREAD

**Issue by typed-sigterm** [becem-gharbi/nuxt-naiveui#81] opened 2024-09-19 16:40 UTC
I finally find this is better than `nuxtjs-naive-ui` ❤️

After upgrading to 2.0.0-rc.1 with Vue 3.5 + Nuxt 3.13, auto-importing stops working:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/naive-ui@2.39.0_vue@3.5.6/node_modules/naive-ui/lib/index.js?v=18f61aba' does not provide an export named 'NLayoutFooter'
```

Reproduction: https://stackblitz.com/edit/nuxt-demo-300f7d0

**Comment by becem-gharbi** [comment] 2024-09-21 07:02
Hi, thanks for reporting this issue. It seems to be a regression on nuxt@3.12.2 related to resolving component's path.

**Comment by becem-gharbi** [comment] 2024-09-29 05:26
Fixed https://github.com/nuxt/nuxt/pull/29036.

**Closed by becem-gharbi** 2024-09-29 05:26 UTC
